### ISSUE TITLE
Problem with windows user

### ISSUE THREAD

**Issue by lozanoco** [vorburger/MariaDB4j#58] opened 2017-01-19 17:10 UTC
Hi,

I'm having a problem because my windows user is "Daniel SMITH" and the ConfigurationBuilder don't recognize it:

ERROR:
ch.vorburger.exec.ManagedProcessException: Asked to wait for "mysqld.exe: ready for connections." from Program [C:\Users\DANIEL~1\AppData\Local\Temp\MariaDB4j\base\bin\mysqld.exe, --no-defaults, --console, --skip-grant-tables, --max_allowed_packet=64M, --basedir="C:\Users\Daniel SMITH\AppData\Local\Temp\MariaDB4j\base", --datadir="C:\Users\Daniel SMITH\AppData\Local\Temp\MariaDB4j\data\3307", --port=3307] (in working directory C:\Users\DANIEL~1\AppData\Local\Temp\MariaDB4j\base), but it already exited! (without that message in console), last 100 lines of console:
...........
C:\Users\DANIEL~1\AppData\Local\Temp\MariaDB4j\base\bin\mysqld.exe: Too many arguments (first extra is 'SMITH\AppData\Local\Temp\MariaDB4j\base').
170119 16:56:13 [ERROR] Aborting

If I configure the ConfigurationBuilder with baseDir, example configurationBuilder.setBaseDir("C:/mariadb");

I have this ERROR:

ch.vorburger.exec.ManagedProcessException: Program [C:\mariadb\bin\mysqld.exe, --no-defaults, --console, --skip-grant-tables, --max_allowed_packet=64M, --basedir=C:\mariadb, --datadir=C:\mariadb, --port=3307] (in working directory C:\mariadb) failed, exitValue=1, last 100 lines of console:
............
170119 18:07:41 [Note] InnoDB: Completed initialization of buffer pool
170119 18:07:41 [ERROR] InnoDB: .\ibdata1 can't be opened in read-write mode
170119 18:07:41 [ERROR] InnoDB: The system tablespace must be writable!
170119 18:07:41 [ERROR] Plugin 'InnoDB' init function returned error.
170119 18:07:41 [ERROR] Plugin 'InnoDB' registration as a STORAGE ENGINE failed.

Thanks

**Comment by paulroemer** [comment] 2017-02-02 05:32
Hi lozanoco,

I may faced the same problem with one of my colleagues. The first error is very likely caused by the space in your user's home directory. But to evaluate that I would need the whole log output.
Then you fixed that bug by as we did by specifying a different tmp and data directory. But to me it looks like you do not have write access to C:/mariadb which causes the second error.

Cheers,
  Paul

**Comment by vorburger** [comment] 2017-02-02 13:50
@lozanoco @paulroemer if it would help to add \" escaping \" somewhere by default in the launch code to avoid this problem on windows, then a pull request with a contribution for this to help other windows users would certainly be welcome..

**Comment by paulroemer** [comment] 2017-02-10 10:12
Hi,

unfortunately the one and only colleague that used Windows now switched to MacOS. And I am using Linux.

My suggestion for others still is to define a base and data directory that does not contain spaces in the path and are read/writable.

But let's see, the Windows machine is still alive and I may get my fingers on it.

**Comment by SmithAdoph** [comment] 2017-04-28 07:55
Hi,
I have the same problem on windows system when reconnect after closing the connection(DbUtils.closeQuietly(conn))!
--
Caused by: ch.vorburger.exec.ManagedProcessException: Asked to wait for "mysqld.exe: ready for connections." from Program [D:\tomcat\apache-tomcat-6.0.18\temp\MariaDB4j\base\bin\mysqld.exe, --no-defaults, --console, --skip-grant-tables, --max_allowed_packet=64M, --basedir=D:\tomcat\apache-tomcat-6.0.18\temp\MariaDB4j\base, --datadir=D:\embed_mysql_db, --port=3309] (in working directory D:\tomcat\apache-tomcat-6.0.18\temp\MariaDB4j\base), but it already exited! (without that message in console), last 100 lines of console:
2017-04-28 15:48:34 24496 [Note] D:\tomcat\apache-tomcat-6.0.18\temp\MariaDB4j\base\bin\mysqld.exe (mysqld 10.1.20-MariaDB) starting as process 29280 ...
2017-04-28 15:48:34 24496 [Note] InnoDB: Using mutexes to ref count buffer pool pages
2017-04-28 15:48:34 24496 [Note] InnoDB: The InnoDB memory heap is disabled
2017-04-28 15:48:34 24496 [Note] InnoDB: Mutexes and rw_locks use Windows interlocked functions
2017-04-28 15:48:34 24496 [Note] InnoDB: _mm_lfence() and _mm_sfence() are used for memory barrier
2017-04-28 15:48:34 24496 [Note] InnoDB: Compressed tables use zlib 1.2.3
2017-04-28 15:48:34 24496 [Note] InnoDB: Using generic crc32 instructions
2017-04-28 15:48:34 24496 [Note] InnoDB: Initializing buffer pool, size = 128.0M
2017-04-28 15:48:34 24496 [Note] InnoDB: Completed initialization of buffer pool
2017-04-28 15:48:34 24496 [ERROR] InnoDB: .\ibdata1 can't be opened in read-write mode
2017-04-28 15:48:34 24496 [ERROR] InnoDB: The system tablespace must be writable!
2017-04-28 15:48:34 24496 [ERROR] Plugin 'InnoDB' init function returned error.
2017-04-28 15:48:34 24496 [ERROR] Plugin 'InnoDB' registration as a STORAGE ENGINE failed.
2017-04-28 15:48:34 24496 [Note] Plugin 'FEEDBACK' is disabled.
2017-04-28 15:48:34 24496 [ERROR] Unknown/unsupported storage engine: InnoDB
2017-04-28 15:48:34 24496 [ERROR] Aborting
at ch.vorburger.exec.ManagedProcess.startAndWaitForConsoleMessageMaxMs(ManagedProcess.java:263)
	at ch.vorburger.mariadb4j.DB.start(DB.java:148)
	... 58 more

**Comment by vorburger** [comment] 2017-04-28 11:08
@SmithAdoph well, your log says "Asked to wait for mysqld.exe but it already exited!", so you need to look up earlier in the log why it exited... I don't think this is the same issue as the original one above, because there don't seem to any spaces in your basedir and datadir?

A pull request to this project with a contribution adding the correct missing escaping would be welcome.

**Comment by SmithAdoph** [comment] 2017-05-08 03:07
@vorburger I've already found the reason for the excepiton because I started the db several times

**Comment by kamaruzzaman** [comment] 2018-05-08 14:06
The problem still exists if directory has space (unfortunately my home directory has space). Here is how to reproduce it:

                DBConfigurationBuilder embeddedDBConfig = DBConfigurationBuilder.newBuilder();
		embeddedDBConfig.setPort(0);
		embeddedDBConfig.setBaseDir("c:\\temp\\MariaDB4j\\nospace");
		embeddedDBConfig.setDataDir("c:\\temp\\MariaDB4j\\with space");

c:\temp\MariaDB4j\nospace\bin\mysqld.exe: Too many arguments (first extra is 'space').
2018-05-08 16:04:42 9924 [ERROR] Aborting

	at ch.vorburger.exec.ManagedProcess.startAndWaitForConsoleMessageMaxMs(ManagedProcess.java:263)
	at ch.vorburger.mariadb4j.DB.start(DB.java:148)
	at de.gelbeseiten.realid.repository.TeilnehmerRepositoryIntegrationTest.setUp(TeilnehmerRepositoryIntegrationTest.java:47)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:61)
	at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:70)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:191)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)

ch.vorburger.exec.ManagedProcessException: An error occurred while starting the database

	at ch.vorburger.mariadb4j.DB.start(DB.java:151)
	at de.gelbeseiten.realid.repository.TeilnehmerRepositoryIntegrationTest.setUp(TeilnehmerRepositoryIntegrationTest.java:47)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:61)
	at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:70)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:191)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: ch.vorburger.exec.ManagedProcessException: Asked to wait for "mysqld.exe: ready for connections." from Program [c:\temp\MariaDB4j\nospace\bin\mysqld.exe, --no-defaults, --console, --skip-grant-tables, --max_allowed_packet=64M, --basedir=C:\temp\MariaDB4j\nospace, --datadir="C:\temp\MariaDB4j\with space", --port=54999] (in working directory c:\temp\MariaDB4j\nospace), but it already exited! (without that message in console), last 100 lines of console:
2018-05-08 16:04:42 9924 [Note] c:\temp\MariaDB4j\nospace\bin\mysqld.exe (mysqld 10.1.20-MariaDB) starting as process 136 ...
2018-05-08 16:04:42 9924 [Note] InnoDB: Using mutexes to ref count buffer pool pages
2018-05-08 16:04:42 9924 [Note] InnoDB: The InnoDB memory heap is disabled
2018-05-08 16:04:42 9924 [Note] InnoDB: Mutexes and rw_locks use Windows interlocked functions
2018-05-08 16:04:42 9924 [Note] InnoDB: _mm_lfence() and _mm_sfence() are used for memory barrier
2018-05-08 16:04:42 9924 [Note] InnoDB: Compressed tables use zlib 1.2.3
2018-05-08 16:04:42 9924 [Note] InnoDB: Using generic crc32 instructions
2018-05-08 16:04:42 9924 [Note] InnoDB: Initializing buffer pool, size = 128.0M
2018-05-08 16:04:42 9924 [Note] InnoDB: Completed initialization of buffer pool
2018-05-08 16:04:42 9924 [Note] InnoDB: Setting log file .\ib_logfile101 size to 48 MB
2018-05-08 16:04:42 9924 [Note] InnoDB: Setting log file .\ib_logfile1 size to 48 MB
2018-05-08 16:04:42 9924 [Note] InnoDB: Renaming log file .\ib_logfile101 to .\ib_logfile0
2018-05-08 16:04:42 9924 [Warning] InnoDB: New log files created, LSN=1623072
2018-05-08 16:04:42 9924 [Note] InnoDB: Highest supported file format is Barracuda.
2018-05-08 16:04:42 9924 [Note] InnoDB: 128 rollback segment(s) are active.
2018-05-08 16:04:42 9924 [Note] InnoDB: Waiting for purge to start
2018-05-08 16:04:42 9924 [Note] InnoDB:  Percona XtraDB (http://www.percona.com) 5.6.34-79.1 started; log sequence number 1623564
2018-05-08 16:04:42 17936 [Note] InnoDB: Dumping buffer pool(s) not yet started
2018-05-08 16:04:42 9924 [Note] Plugin 'FEEDBACK' is disabled.
c:\temp\MariaDB4j\nospace\bin\mysqld.exe: Too many arguments (first extra is 'space').
2018-05-08 16:04:42 9924 [ERROR] Aborting

**Comment by vorburger** [comment] 2018-05-14 14:10
A contribution to this project in the form of a Pull Request from a Windows user which fixes this problem for other fellow windows users would certainly be welcome. (Personally I don't use Windows.)

**Comment by ZeroTau** [comment] 2018-06-22 02:11
I am taking a look at this and am getting conflicting signals. When I run the MariaDB4jSampleDumpTest as a user with space in my home directory on Window10 the test fails with the following error:
```
[C:\Users\ANDREW~1\AppData\Local\Temp\MariaDB4j\base\bin\mysql_install_db.exe, --datadir="C:\Users\Andrew Mertz\AppData\Local\Temp\MariaDB4j\data\60582"] (in working directory C:\Users\ANDREW~1\AppData\Local\Temp\MariaDB4j\base\bin)
[Exec Stream Pumper] INFO ch.vorburger.exec.ManagedProcess - mysql_install_db.exe: Running bootstrap
[Exec Stream Pumper] ERROR ch.vorburger.exec.ManagedProcess - mysql_install_db.exe: FATAL ERROR: Cannot set current directory to 'C:\Users\Andrew'
```
However, all of the paths up to when `mysql_install_db.exe` is started are the correct shorthand. The fatal error looks to be reported by `mysql_install_db.exe` itself as `mysql_install_db.exe` is started. Also, if I replace `mysql_install_db.exe` with a mock exe in the same location the test runs fine up to that point. At the same time, I can run this exact command from a shell and the install runs fine. So I am not quite sure where to go from here. Any thoughts?

**Comment by vorburger** [comment] 2018-06-22 09:40
> if I replace mysql_install_db.exe with a mock exe in the same location the test runs fine 
> mysql_install_db.exe: FATAL ERROR: Cannot set current directory to 'C:\Users\Andrew'

doesn't this mean that it is `mysql_install_db.exe` itself, more than _MariaDB4j,_ which doesn't handle the space in that `datadir` argument? Does it work / what happens if you just open a command prompt and do the equivalent manually:

    C:\> cd C:\Users\ANDREW~1\AppData\Local\Temp\MariaDB4j\base\bin
    C:\Users\ANDREW~1\AppData\Local\Temp\MariaDB4j\base\bin> C:\Users\ANDREW~1\AppData\Local\Temp\MariaDB4j\base\bin\mysql_install_db.exe, --datadir="C:\Users\Andrew Mertz\AppData\Local\Temp\MariaDB4j\data\60582"

**Comment by ZeroTau** [comment] 2018-06-22 15:44
That is the thing, if I run the command manually from either powershell or cmd it works. I literally copied and pasted the string form of the commandline object MariaDB4j made and it runs without error. When I get a chance today I am going try having MariaDB4j open a shell to run the command in.

**Comment by ZeroTau** [comment] 2018-06-22 17:47
Even when I add a `cmd /C` to the command `mysql_install_db.exe` still reports a `FATAL ERROR: Cannot set current directory`.

**Comment by ZeroTau** [comment] 2018-06-22 20:00
I have been able to get `mysql_install_db.exe` to install by changing the `ManagedProcessBuilder` to run it with `cmd /C` and using the `-d` flag to give a relative path to the data directory. However, after this starting `mysqld` fails as it is looking for files in a wrong location (missing space in a path).

**Comment by ZeroTau** [comment] 2018-06-22 20:17
Just using the flag `-d` and a relative path also works for getting `mysql_install_db.exe` to install.

**Comment by wangdongya** [comment] 2019-02-14 06:19
I have the same problem as the provider, Is this problem solved?

Caused by: ch.vorburger.exec.ManagedProcessException: Asked to wait for "mysqld.exe: ready for connections." from Program [C:\Users\WD\AppData\Local\Temp\MariaDB4j\base\bin\mysqld.exe, --no-defaults, --console, --skip-grant-tables, --max_allowed_packet=64M, --basedir=C:\Users\WD\AppData\Local\Temp\MariaDB4j\base, --datadir=D:\project\progream\data\local\temp, --port=3307] (in working directory C:\Users\WD\AppData\Local\Temp\MariaDB4j\base), but it already exited! (without that message in console), last 100 lines of console:
 779932 [Note] C:\Users\WD\AppData\Local\Temp\MariaDB4j\base\bin\mysqld.exe (mysqld 10.1.20-MariaDB) starting as process 52792 ...
 [Note] InnoDB: Using mutexes to ref count buffer pool pages
 [Note] InnoDB: The InnoDB memory heap is disabled
 [Note] InnoDB: Mutexes and rw_locks use Windows interlocked functions
 [Note] InnoDB: _mm_lfence() and _mm_sfence() are used for memory barrier
 InnoDB: Compressed tables use zlib 1.2.3
InnoDB: Using generic crc32 instructions
 InnoDB: Initializing buffer pool, size = 128.0M
InnoDB: Completed initialization of buffer pool
 InnoDB: .\ibdata1 can't be opened in read-write mode
 InnoDB: The system tablespace must be writable!
 Plugin 'InnoDB' init function returned error.
 Plugin 'InnoDB' registration as a STORAGE ENGINE failed.
Plugin 'FEEDBACK' is disabled.
 Unknown/unsupported storage engine: InnoDB
 Aborting

**Comment by SmithAdoph** [comment] 2019-02-14 06:25
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        Check to see if you have started the database multiple times
            
        
    
    
        
            
        
    
    
     
    
        
                    
            
                
                    
                            
                                
                            
                            
                                314309413
                            
                    
                        
                            
                                    314309413@qq.com
                            
                        
                
            
        
        
    
    
        签名由
        网易邮箱大师
        定制
    
 

    On 2/14/2019 14:19，wangdongya<notifications@github.com> wrote： 


I have the same problem as the provider, Is this problem solved?
Caused by: ch.vorburger.exec.ManagedProcessException: Asked to wait for "mysqld.exe: ready for connections." from Program [C:\Users\WD\AppData\Local\Temp\MariaDB4j\base\bin\mysqld.exe, --no-defaults, --console, --skip-grant-tables, --max_allowed_packet=64M, --basedir=C:\Users\WD\AppData\Local\Temp\MariaDB4j\base, --datadir=D:\project\progream\data\local\temp, --port=3307] (in working directory C:\Users\WD\AppData\Local\Temp\MariaDB4j\base), but it already exited! (without that message in console), last 100 lines of console:
779932 [Note] C:\Users\WD\AppData\Local\Temp\MariaDB4j\base\bin\mysqld.exe (mysqld 10.1.20-MariaDB) starting as process 52792 ...
[Note] InnoDB: Using mutexes to ref count buffer pool pages
[Note] InnoDB: The InnoDB memory heap is disabled
[Note] InnoDB: Mutexes and rw_locks use Windows interlocked functions
[Note] InnoDB: _mm_lfence() and _mm_sfence() are used for memory barrier
InnoDB: Compressed tables use zlib 1.2.3
InnoDB: Using generic crc32 instructions
InnoDB: Initializing buffer pool, size = 128.0M
InnoDB: Completed initialization of buffer pool
InnoDB: .\ibdata1 can't be opened in read-write mode
InnoDB: The system tablespace must be writable!
Plugin 'InnoDB' init function returned error.
Plugin 'InnoDB' registration as a STORAGE ENGINE failed.
Plugin 'FEEDBACK' is disabled.
Unknown/unsupported storage engine: InnoDB
Aborting

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by wangdongya** [comment] 2019-02-14 06:42
> 检查您是否多次启动数据库

This problem occurs even if the database is started for the first time.

**Comment by wangdongya** [comment] 2019-02-14 06:43
> Check to see if you have started the database multiple times

Do you have a good solution?

**Comment by SmithAdoph** [comment] 2019-02-14 06:49
> > Check to see if you have started the database multiple times
> 
> Do you have a good solution?
几年前遇到的问题了，可以跟下启动的代码

**Comment by wangdongya** [comment] 2019-02-14 06:54
> Just using the flag `-d` and a relative path also works for getting `mysql_install_db.exe` to install.
> 
> However, now I am getting the following error when I try to start `mysqld.exe`
> 
> ```
> [main] INFO ch.vorburger.exec.ManagedProcess - Thread will wait for "mysqld.exe: ready for connections." to appear in Console output of process Program [C:\Users\Andrew Mertz\AppData\Local\Temp\MariaDB4j\base\bin\mysqld.exe, --no-defaults, --console, --skip-grant-tables, --max_allowed_packet=64M, --basedir="C:\Users\Andrew Mertz\AppData\Local\Temp\MariaDB4j\base", --datadir="C:\Users\Andrew Mertz\AppData\Local\Temp\MariaDB4j\data\51153", --lc-messages-dir="C:\Users\Andrew Mertz\AppData\Local\Temp\MariaDB4j\base\share", --port=51153] (in working directory C:\Users\ANDREW~1\AppData\Local\Temp\MariaDB4j\base) for max. 30000ms
> [Exec Stream Pumper] INFO ch.vorburger.exec.ManagedProcess - mysqld.exe: 2018-06-22 15:46:16 2212 [Note] C:\Users\Andrew Mertz\AppData\Local\Temp\MariaDB4j\base\bin\mysqld.exe (mysqld 10.2.11-MariaDB) starting as process 17132 ...
> [Exec Stream Pumper] ERROR ch.vorburger.exec.ManagedProcess - mysqld.exe: 2018-06-22 15:46:16 2212 [ERROR] Can't find messagefile 'C:\Users\Andrew\errmsg.sys'
> [Exec Stream Pumper] ERROR ch.vorburger.exec.ManagedProcess - mysqld.exe: 2018-06-22 15:46:16 2212 [ERROR] Aborting
> ```
> Note I added the `--lc-messages-dir` flag to try to show `mysqld` where the missing file was to no avail.
> 
> I changed the `--lc-messages-dir` flag to a relative one and I no longer have the above error, but I am stuck again on a "No such file or directory" error due to an unquoted space.
> 
> ```
> [main] INFO ch.vorburger.exec.ManagedProcess - Thread will wait for "mysqld.exe: ready for connections." to appear in Console output of process Program [C:\Users\Andrew Mertz\AppData\Local\Temp\MariaDB4j\base\bin\mysqld.exe, --no-defaults, --console, --skip-grant-tables, --max_allowed_packet=64M, --basedir="C:\Users\Andrew Mertz\AppData\Local\Temp\MariaDB4j\base", --datadir="C:\Users\Andrew Mertz\AppData\Local\Temp\MariaDB4j\data\51223", --language=./share, --port=51223] (in working directory C:\Users\ANDREW~1\AppData\Local\Temp\MariaDB4j\base) for max. 30000ms
> [Exec Stream Pumper] INFO ch.vorburger.exec.ManagedProcess - mysqld.exe: 2018-06-22 16:05:02 18096 [Note] C:\Users\Andrew Mertz\AppData\Local\Temp\MariaDB4j\base\bin\mysqld.exe (mysqld 10.2.11-MariaDB) starting as process 8468 ...
> [Exec Stream Pumper] INFO ch.vorburger.exec.ManagedProcess - mysqld.exe: 2018-06-22 16:05:02 18096 [Warning] Can't create test file C:\Users\Andrew\Albedo.lower-test
> [Exec Stream Pumper] INFO ch.vorburger.exec.ManagedProcess - mysqld.exe: �C:\Users\Andrew Mertz\AppData\Local\Temp\MariaDB4j\base\bin\mysqld.exe: Can't change dir to 'C:\Users\Andrew\' (Errcode: 2 "No such file or directory")
> [Exec Stream Pumper] ERROR ch.vorburger.exec.ManagedProcess - mysqld.exe: 2018-06-22 16:05:02 18096 [ERROR] Aborting
> ```
The same problem occurs when the path to the basedir is specified as mariadb's mysqld path.

**Comment by vorburger** [comment] 2019-02-14 19:45
Hi guys, I don't work with Windows (only Linux), but I would very much welcome a Pull Request to this project from any of you if you can improve it for Windows! Thanks a lot for contributing to this Open Source project.

**Comment by vorburger** [comment] 2019-03-09 15:54
#229 probably fixed this issue - can you guys who hit it here verify that?

**Closed** 2019-09-02 06:32 UTC
Labels: Windows, helpwanted, low
