### ISSUE TITLE
Maria4j Managed process does not start correctly  if "log-error" is defined in the configuration 

### ISSUE THREAD

**Issue by venkat-raman** [vorburger/MariaDB4j#69] opened 2017-04-26 20:33 UTC
As a part of getting a error logs, i added "--log-error=error.log" location as part of my configuration for DB Startup. This is meant to redirect stderr to error.log file. Due to this Parent Process fails with the error "Caused by: ch.vorburger.exec.ManagedProcessException: Database does not seem to have started up correctly? Magic string not seen in 30000ms: mysqld: ready for connections". My guess is that parent process which is looking for string "mysqld: ready for connections" does not find as it looking for it in console, but now this is getting written to error.log. 

I am wondering if anybody else has faced this issue and if there is a known workaround.

**Comment by vorburger** [comment] 2017-06-16 00:51
@venkat-raman the idea with this "embedded" library is more that the log from the DB goes into your "normal" Java application log, through [the slf4j logging API](https://www.slf4j.org), which [using e.g. logback you can configure to go into a file](https://logback.qos.ch). You could even configure logback to write the logs from mariaDB4j into a separate file.

So your "--log-error=error.log"  approach is probably typically not used (with MariaDB4j). If you have strong reasons to have to use that instead of "normal" Java logging, then you may be able to achieve what you're after by subclassing the DB class and tweaking how it sets up the logging interception.... (but it's probably easier to use it as intended & as most people do.)

Hope this helps? If I don't hear back from you on this issue, I'll be closing it in 1 month.

**Comment by tugalsan** [comment] 2017-09-13 06:39
I have recently compiled my war file into an executable jar with embeding tomcat and maria. 
Eveerything worked fine on simple tests. But when i tried to run on server with MYSQL data,
I get similiar Exception. 

I wish is the same that, we could come up with a fix:

`
ProgramDir: (D:\autosqlweb\)
starting MariaDB on loc [D:\autosqlweb\mariaDBData]...
ch.vorburger.exec.ManagedProcessException: An error occurred while installing the database
	at ch.vorburger.mariadb4j.DB.install(DB.java:129)
	at ch.vorburger.mariadb4j.DB.newEmbeddedDB(DB.java:76)
	at com.tugalsan.autosqlweb.TK_GWTSQLMariaDB.<init>(TK_GWTSQLMariaDB.java:30)
	at com.tugalsan.autosqlweb.Main.main(Main.java:37)
Caused by: ch.vorburger.exec.ManagedProcessException: Program [C:\Users\tugalsan\AppData\Local\Temp\3\MariaDB4j\base\bin\mysql_install_db.exe, --datadir=D:\autosqlweb\mariaDBData] (in working directory C:\Users\tugalsan\AppData\Local\Temp\3\MariaDB4j\base) failed, exitValue=1, last 100 lines of console:
Running bootstrap
2017-09-13  9:16:04 7604 [Note] C:\Users\tugalsan\AppData\Local\Temp\3\MariaDB4j\base\bin\mysqld.exe (mysqld 10.1.20-MariaDB) starting as process 7584 ...
ERROR: Cannot write to mysqld's stdin
FATAL ERROR: database creation failed
https://mariadb.com/kb/en/installation-issues-on-windows contains some help
for solving the most common problems.  If this doesn't help you, please
leave a comment in the Knowledge Base or file a bug report at
https://jira.mariadb.org
	at ch.vorburger.exec.ManagedProcess.checkResult(ManagedProcess.java:297)
	at ch.vorburger.exec.ManagedProcess.waitForExitMaxMsWithoutLog(ManagedProcess.java:415)
	at ch.vorburger.exec.ManagedProcess.waitForExit(ManagedProcess.java:385)
	at ch.vorburger.mariadb4j.DB.install(DB.java:127)
	... 3 more
Caused by: org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1)
	at org.apache.commons.exec.DefaultExecutor.executeInternal(DefaultExecutor.java:404)
	at org.apache.commons.exec.DefaultExecutor.access$200(DefaultExecutor.java:48)
	at org.apache.commons.exec.DefaultExecutor$1.run(DefaultExecutor.java:200)
	at java.lang.Thread.run(Unknown Source)
`

**Comment by vorburger** [comment] 2018-01-13 01:40
Closing issue due to non-response from reporter.

PS: If someone else wants to contribute a PR for this, go for it...

**Closed by vorburger** 2018-01-13 01:40 UTC
Labels: helpwanted, low
