### ISSUE TITLE
Hoping someone can assist ...

### ISSUE THREAD

**Issue by EasyG0ing1** [vorburger/MariaDB4j#350] opened 2020-05-15 09:53 UTC
I'm running MacOS Catalina, and When I tried to get MariaDB4J to install, I was getting all kinds of errors, but in the deep of the feedback I saw a suggestion to run a command from terminal which I did. And this is what it came back with:

```
~ $/private/var/folders/31/wvbpnk3d609fm8x1ppxxxcsr0000gr/T/MariaDB4j/base/bin/mysqld --skip-grant --general-log &
[1] 32703
dyld: Library not loaded: /usr/local/opt/openssl/lib/libssl.1.0.0.dylib
  Referenced from: /private/var/folders/31/wvbpnk3d609fm8x1ppxxxcsr0000gr/T/MariaDB4j/base/bin/mysqld
  Reason: image not found
[1]+  Abort trap: 6           /private/var/folders/31/wvbpnk3d609fm8x1ppxxxcsr0000gr/T/MariaDB4j/base/bin/mysqld --skip-grant --general-log
```

Now, I totally understand what it wants, and I was able to fix it by copying that file and libcrypto.dylib into the folder it was looking in ... but here is where I'm stuck and don't know where to go next:

**WHY was it looking in that folder for that file?**  What (something - variable, path setting or whatever) is in existence somewhere that is making it think that the library file is in that folder instead of the folder where it actually did exist?  

I'm not too keen on moving files like that around because one upgrade later and it's broke again, **I'd rather understand where the  'pointer' to that file is so I can fix the pointer properly.**

Thank you,

Michael

**Comment by crummy** [comment] 2020-06-04 03:42
For what it's worth, I'm on Catalina too (10.15.2) and I get the same error:
```
dyld: Library not loaded: /usr/local/opt/openssl/lib/libssl.1.0.0.dylib
```

**Comment by EasyG0ing1** [comment] 2020-06-29 07:18
> For what it's worth, I'm on Catalina too (10.15.2) and I get the same error:
> 
> ```
> dyld: Library not loaded: /usr/local/opt/openssl/lib/libssl.1.0.0.dylib
> ```

You need to search your hard drive for the file 'libssl.1.0.0.dylib' then copy it to the folder '/usr/local/opt/openssl/lib/' ... you'll need to do this as root. Once you do, it should work.

**Comment by A248** [comment] 2020-09-04 18:26
Rather than copy the files, you can symlink them, as shown here: https://github.com/vorburger/MariaDB4j/issues/48#issuecomment-574391644
(This issue is a duplicate of that one)

**Comment by EasyG0ing1** [comment] 2020-09-11 18:33
> Rather than copy the files, you can symlink them, as shown here: [#48 (comment)](https://github.com/vorburger/MariaDB4j/issues/48#issuecomment-574391644)
> (This issue is a duplicate of that one)

Good call on the symlink!

**Comment by vorburger** [comment] 2020-10-19 22:30
Can we close this issue?

**Comment by luigiberrettini** [comment] 2020-10-20 21:59
Yes it is a duplicate

**Closed** 2020-12-14 14:39 UTC
