### ISSUE TITLE
java.lang.NoSuchMethodError: org.apache.commons.io.FileUtils.deleteQuietly

### ISSUE THREAD

**Issue by benjamin-olx** [vorburger/MariaDB4j#75] opened 2017-06-20 11:08 UTC
First let me say thanks for this great tool!

I encountered an error in the logs:

```
10:59:30.477 [Shutdown Hook Deletion Thread for Temporary DB /tmp/MariaDB4j/data/3306] INFO ch.vorburger.mariadb4j.DB - cleanupOnExit() ShutdownHook quietly deleting temporary DB data directory: /tmp/MariaDB4j/data/3306
10:59:30.477 [Shutdown Hook Deletion Thread for Temporary DB /tmp/MariaDB4j/data/3306] INFO ch.vorburger.mariadb4j.DB - cleanupOnExit() ShutdownHook quietly deleting temporary DB data directory: /tmp/MariaDB4j/data/3306
Exception in thread "Shutdown Hook Deletion Thread for Temporary DB /tmp/MariaDB4j/data/3306" java.lang.NoSuchMethodError: org.apache.commons.io.FileUtils.deleteQuietly(Ljava/io/File;)Z
	at ch.vorburger.mariadb4j.DB$1.run(DB.java:369)
```

Do I need to declare a dependency to Apache Commons in my project?

I am using mariaDB4j version 2.2.3.

**Comment by vorburger** [comment] 2017-06-20 11:16
Closing as duplicate of https://github.com/vorburger/MariaDB4j/issues/73.

**Closed by vorburger** 2017-06-20 11:16 UTC

**Comment by vorburger** [comment] 2017-07-15 14:13
[Standard Footer] PS: Shameless plug, consider https://www.patreon.com/vorburger to support MariaDB4j.
