### ISSUE TITLE
The storage engine InnoDB doesn't support SPATIAL indexes

### ISSUE THREAD

**Issue by vlad-chromeriver** [vorburger/MariaDB4j#104] opened 2018-02-23 23:43 UTC
Hello, can someone recommend a solution to this?

The query I'm trying to run is:

```
DROP TABLE IF EXISTS `nav_AccountIncomingData`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `nav_AccountIncomingData` (
  `AccountIncomingDataId` int(11) NOT NULL AUTO_INCREMENT,
  `CustomerId` int(11) NOT NULL,
  `AccountId` varchar(18) DEFAULT NULL,
  `AccountName` varchar(255) DEFAULT NULL,
  `AccountOwnerId` int(11) DEFAULT NULL,
  `CRMAccountOwnerId` varchar(18) DEFAULT NULL,
  `TaskId` varchar(100) NOT NULL,
  `TaskCreateDate` datetime NOT NULL,
  `TaskUpdateDate` datetime NOT NULL,
  `Status` varchar(20) NOT NULL,
  `LocationId` int(11) NOT NULL,
  `City` varchar(155) DEFAULT NULL,
  `Country` varchar(155) DEFAULT NULL,
  `State` varchar(25) DEFAULT NULL,
  `Zipcode` varchar(25) DEFAULT NULL,
  `Street` varchar(255) DEFAULT NULL,
  `Lat` decimal(10,8) DEFAULT NULL,
  `Lng` decimal(11,8) DEFAULT NULL,
  `point` point NOT NULL,
  PRIMARY KEY (`AccountIncomingDataId`),
  UNIQUE KEY `accounts_account_id_uindex` (`AccountIncomingDataId`),
  UNIQUE KEY `locations_UN` (`Street`,`Lng`,`Lat`),
  SPATIAL INDEX(`point`)
) ENGINE=InnoDB AUTO_INCREMENT=2267 DEFAULT CHARSET=utf8;
/*!40101 SET character_set_client = @saved_cs_client */;
```

The exception is:

```
[main] ERROR ch.vorburger.exec.ManagedProcess - Program [/var/folders/5y/rpv8v4817d93fcs5wpx48g880000gp/T/MariaDB4j/base/bin/mysql, --socket=/private/var/folders/5y/rpv8v4817d93fcs5wpx48g880000gp/T/MariaDB4j.53375.sock] (in working directory /var/folders/5y/rpv8v4817d93fcs5wpx48g880000gp/T/MariaDB4j/base) failed
[main] ERROR com.chromeriver.TestExpensePersonRecord - unable to start embedded db
ch.vorburger.exec.ManagedProcessException: An error occurred while running a script file sourced from the classpath at: createPersonTable.sql
	at ch.vorburger.mariadb4j.DB.run(DB.java:270)
	at ch.vorburger.mariadb4j.DB.source(DB.java:238)
	at ch.vorburger.mariadb4j.DB.source(DB.java:221)
	at com.chromeriver.TestExpensePersonRecord.before(TestExpensePersonRecord.java:68)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.springframework.test.context.junit4.statements.RunBeforeTestMethodCallbacks.evaluate(RunBeforeTestMethodCallbacks.java:75)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.springframework.test.context.junit4.statements.RunAfterTestMethodCallbacks.evaluate(RunAfterTestMethodCallbacks.java:86)
	at org.springframework.test.context.junit4.statements.SpringRepeat.evaluate(SpringRepeat.java:84)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:252)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:94)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:61)
	at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:70)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:191)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: ch.vorburger.exec.ManagedProcessException: Program [/var/folders/5y/rpv8v4817d93fcs5wpx48g880000gp/T/MariaDB4j/base/bin/mysql, --socket=/private/var/folders/5y/rpv8v4817d93fcs5wpx48g880000gp/T/MariaDB4j.53375.sock] (in working directory /var/folders/5y/rpv8v4817d93fcs5wpx48g880000gp/T/MariaDB4j/base) failed, exitValue=1, last 100 lines of console:
ERROR 1464 (HY000) at line 48: The storage engine InnoDB doesn't support SPATIAL indexes
	at ch.vorburger.exec.ManagedProcess.checkResult(ManagedProcess.java:297)
	at ch.vorburger.exec.ManagedProcess.startExecute(ManagedProcess.java:207)
	at ch.vorburger.exec.ManagedProcess.start(ManagedProcess.java:134)
	at ch.vorburger.mariadb4j.DB.run(DB.java:267)
	... 32 more
Caused by: org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1)
	at org.apache.commons.exec.DefaultExecutor.executeInternal(DefaultExecutor.java:404)
	at org.apache.commons.exec.DefaultExecutor.access$200(DefaultExecutor.java:48)
	at org.apache.commons.exec.DefaultExecutor$1.run(DefaultExecutor.java:200)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by vorburger** [comment] 2018-02-26 15:25
@vlad-chromeriver not sure this is a question for MariaDB**4j**, this java library, or rather a general MariaDB (the actual underlying data base) .. have you tried to just [search for the "The storage engine InnoDB doesn't support SPATIAL indexes"](https://www.google.ch/search?q=The+storage+engine+InnoDB+doesn%27t+support+SPATIAL+indexes) root cause error message?

Perhaps (not sure) this is "just" an issue of the native MariaDB version? In that case, you would have to [contribute a new native MariaDB version to MariaDB4j](https://github.com/vorburger/MariaDB4j#mariadb-database-jars-and-version-upgrades) ... 

Can you let us know your findings? I'll close this issue 1 month after the last reply.

**Comment by vlad-chromeriver** [comment] 2018-02-26 19:50
Thank you for the reply @vorburger you can close this issue now, if you like, because I have another path forward, to launch mysql in a docker container using testcontainers.org

**Closed** 2018-02-26 20:21 UTC
