### ISSUE TITLE
Include under binaries the backup/restore tools

### ISSUE THREAD

**Issue by cortiz** [vorburger/MariaDB4j#65] opened 2017-04-07 14:23 UTC
mysqldump and mysqlimport should be available so we could make portable backups.

**Comment by vorburger** [comment] 2017-04-07 19:30
@cortiz thanks for your interest in this project. I've nothing against including additional such binaries into the DB JARs, and perhaps even having methods in the Java APIs to nicely expose these utilities?

If you would like to contribute this to the project, please [see the relevant section on the README](https://github.com/vorburger/MariaDB4j/blob/master/README.md#mariadb-database-jars-and-version-upgrades).

**Comment by cortiz** [comment] 2017-05-23 19:13
This should be solve in PR#71

**Comment by vorburger** [comment] 2017-06-16 00:44
Closing this as a duplicate of the now ongoing and (if you could incorporate the review feedback) about to be merged https://github.com/vorburger/MariaDB4j/pull/71 - no need t keep this issue here open separately anymore now.

**Closed by vorburger** 2017-06-16 00:44 UTC
Labels: helpwanted, low
