### ISSUE TITLE
Outdated maven repository?

### ISSUE THREAD

**Issue by adriananghel1999** [vorburger/MariaDB4j#425] opened 2021-03-15 20:15 UTC
Hello, i'm trying to use this library and I have a problem related with getting the source from a .sql:

I'm trying to pick up the .sql source from outside a .jar, I put the .sql in the same folder as the generated .jar and it tells me it's not inside. I use db.source("./data.sql", "databasename") I do not know if it is correct, I have not worked much with InputStreams, anyway, I have looked in this repository the source method of the DB class and it is more developed than the one that comes in version 2.4.0 through Maven. Can someone help me?

**Comment by adriananghel1999** [comment] 2021-03-20 19:44
If anyone has an alternative solution to my problem please I will be very grateful.

**Comment by vorburger** [comment] 2021-06-27 18:38
@adriananghel1999 yeah, I haven't had the time recently to maintain this project.

I'll close this issue as a duplicate of #334.

**Closed by vorburger** 2021-06-27 18:38 UTC
